// This file has been generated by Specta. DO NOT EDIT.

export type PasswordCredentials = { username: string; password: string }

export type ApiError = "InternalError" | "Unauthorized" | { InvalidInput: ([string, string])[] } | { Message: string }

