[package]
name = "auxy_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auxy = { version = "*", path = "../core" }
axum = "0.7.2"
const_format = "0.2.32"
log = { version = "0.4.20", features = ["max_level_info"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_qs = { version = "0.12.0", features = ["axum"] }
stderrlog = "0.5.4"
tokio = { version = "1.35.0", features = ["full"] }
