CREATE TABLE users (
    id BIGINT PRIMARY KEY NOT NULL,
    username VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE auth (
    id BIGINT PRIMARY KEY NOT NULL,
    password VARCHAR(255) NOT NULL,
    session_token VARCHAR(255) NULL,

	CONSTRAINT auth_id_foreign FOREIGN KEY(id) REFERENCES users(id)
);
